language: php

php:
  - 5.6

install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - vendor/bin/coveralls -v